config/routes.rb
MetadataPresenter::Engine.routes.draw do
  root to: 'service#start'

  get  '/auth', to: 'auth#show'
  post '/auth', to: 'auth#create'

  post '/reserved/submissions', to: 'submissions#create', as: :reserved_submissions
  get '/reserved/change-answer', to: 'change_answer#create', as: :change_answer

  # We are not adding rails ujs to the editor app so we need to make it
  # as get verb.
  get '/reserved/file/:component_id', to: 'file#destroy', as: :remove_file
  get '/reserved/file/:component_id/:file_uuid', to: 'file#remove_multifile', as: :remove_multifile

  get 'session/expired', to: 'session#expired'
  get 'session/complete', to: 'session#complete'
  get 'session/destroyed', to: 'session#destroyed'

  # save form journey
  get 'save', to: 'save_and_return#show'
  post 'saved_forms', to: 'save_and_return#create'
  get 'save/email_confirmation', to: 'save_and_return#email_confirmation'
  post 'email_confirmations', to: 'save_and_return#confirm_email'
  get 'save/progress_saved', to: 'save_and_return#save_progress'

  # resume form journey
  get '/return/:uuid', to: 'resume#return'
  post 'resume_forms', to: 'resume#submit_secret_answer'
  get 'resume_from_start', to: 'resume#resume_from_start'
  get 'resume_progress', to: 'resume#resume_progress'
  get 'record_error', to: 'resume#record_error'
  get 'record_failure', to: 'resume#record_failure'
  get 'expired', to: 'resume#record_link_expired'
  get 'already_used', to: 'resume#record_link_used'

  post '/', to: 'answers#create'
  match '*path', to: 'answers#create', via: :post
  match '*path', to: 'pages#show',
    via: :all,
    constraints: lambda {|req| req.path !~ /\.(png|jpg|js|css|ico)$/ }
end

app/models/metadata_presenter/address_fieldset.rb
module MetadataPresenter
  class AddressFieldset
    extend ActiveModel::Translation
    include ActiveModel::Validations
    include ActionView::Helpers
    include SpecialCharacterUnescaper

    DEFAULT_COUNTRY = 'United Kingdom'.freeze
    FIELDS = %w[
      address_line_one
      address_line_two
      city
      county
      postcode
      country
    ].freeze

    attr_reader(*FIELDS)

    def initialize(address)
      FIELDS.each do |field|
        next unless address[field]

        instance_variable_set(:"@#{field}", conform(address[field]))
      end

      @country ||= DEFAULT_COUNTRY
    end

    def to_a
      as_json.values.compact_blank
    end

    def as_json
      super(only: FIELDS)
    end

    def conform(address_field)
      unescape_special_characters(sanitize(address_field, tags: [], attributes: []).strip)
    end
  end
end

app/models/metadata_presenter/auth_form.rb
module MetadataPresenter
  class AuthForm
    include ActiveModel::Model

    attr_accessor :username, :password

    validates :username, :password,
              presence: true, allow_blank: false

    validate :valid_credentials

    private

    def valid_credentials
      errors.add(:base, :unauthorised) unless errors.any? || authorised?
    end

    def authorised?
      # This comparison uses & so that it doesn't short circuit and
      # uses `secure_compare` so that length information isn't leaked.
      ActiveSupport::SecurityUtils.secure_compare(env_username, username) &
        ActiveSupport::SecurityUtils.secure_compare(env_password, password)
    end

    def env_username
      ENV['BASIC_AUTH_USER'].to_s
    end

    def env_password
      ENV['BASIC_AUTH_PASS'].to_s
    end
  end
end

app/models/metadata_presenter/autocomplete_item.rb
class MetadataPresenter::AutocompleteItem < MetadataPresenter::Metadata
  def id
    { text:, value: }.to_json
  end

  def name
    text
  end
end

app/models/metadata_presenter/branch_destinations.rb
module MetadataPresenter
  module BranchDestinations
    # The frontend requires that expressions of type 'or' get there own line and
    # arrow. 'and' expression types continue to be grouped together.
    # Return the UUIDs of the destinations exiting a branch and allow duplicates
    # if the expression type is an 'or'.
    def exiting_destinations_from_branch(branch)
      destination_uuids = branch.conditionals.map do |conditional|
        if conditional.type == 'or'
          conditional.expressions.map { |_| conditional.next }
        else
          conditional.next
        end
      end
      destination_uuids.flatten.push(branch.default_next)
    end

    def has_or_conditionals?(branch)
      branch.conditionals.any? { |c| c.type == 'or' }
    end
  end
end

app/models/metadata_presenter/column_number.rb
module MetadataPresenter
  class ColumnNumber
    def initialize(uuid:, coordinates:, new_column:, service:)
      @uuid = uuid
      @coordinates = coordinates
      @new_column = new_column
      @service = service
    end

    def number
      if service.flow_object(uuid).branch?
        # Even though we are associating the column number to a specific flow object
        # in the Coordinates model we do not use column_number + 1 as we are
        # updating the position for the Spacers that exist for a branch which
        # are always in the same column as the branch object itself.
        coordinates.set_branch_spacers_column(uuid, column_number)
      end

      column_number
    end

    private

    attr_reader :uuid, :coordinates, :new_column, :service

    def column_number
      @column_number ||= begin
        return last_column if confirmation_page?
        return latest_column if checkanswers_page?

        existing_column || new_column
      end
    end

    def confirmation_page?
      service.confirmation_page&.uuid == uuid
    end

    def checkanswers_page?
      service.checkanswers_page&.uuid == uuid
    end

    def latest_column
      [existing_column, new_column].compact.max
    end

    def last_column
      checkanswers_column.present? ? checkanswers_column + 1 : latest_column
    end

    def checkanswers_column
      @checkanswers_column ||= begin
        return if service.checkanswers_page.blank?

        coordinates.uuid_column(service.checkanswers_page&.uuid)
      end
    end

    def existing_column
      @coordinates.uuid_column(uuid)
    end
  end
end

app/models/metadata_presenter/component.rb
class MetadataPresenter::Component < MetadataPresenter::Metadata
  include Comparable

  VALIDATION_BUNDLES = {
    'date' => 'date',
    'number' => 'number',
    'text' => 'string',
    'textarea' => 'string',
    'multiupload' => 'file'
  }.freeze

  # Used for max_length and max_word validations.
  # Threshold percentage at which the remaining count is shown
  VALIDATION_STRING_LENGTH_THRESHOLD = 75

  def <=>(other)
    return nil unless other.is_a?(MetadataPresenter::Component)
    return 0 unless order && other.order

    order <=> other.order
  end

  # Overriding here because autocomplete component's items property is non interactable
  # in the Editor therefore it does not need to exist in the data-fb-content-data
  # attribute on the page. The data-fb-content-data attribute is what is used to
  # update user interactable elements such as the component question or page section
  # heading etc.
  def to_json(*_args)
    return super unless autocomplete?

    JSON.parse(super).to_json(except: 'items')
  end

  def to_partial_path
    "metadata_presenter/component/#{type}"
  end

  def humanised_title
    label || legend
  end

  def items
    Array(metadata.items).map do |item|
      item_klass.new(item, editor: editor?)
    end
  end

  def item_klass
    autocomplete? ? MetadataPresenter::AutocompleteItem : MetadataPresenter::Item
  end

  SUPPORTS_BRANCHING = %w[radios checkboxes].freeze

  def supports_branching?
    type.in?(SUPPORTS_BRANCHING)
  end

  def autocomplete?
    type == 'autocomplete'
  end

  def content?
    type == 'content'
  end

  def upload?
    type == 'upload'
  end

  def multiupload?
    type == 'multiupload'
  end

  def find_item_by_uuid(uuid)
    items.find { |item| item.uuid == uuid }
  end

  def supported_validations
    return [] if validation_bundle_key.nil?

    JSON::Validator.schema_for_uri(validation_bundle_key)
                   .schema['properties']['validation']['properties']
                   .keys
  end

  def validation_threshold
    VALIDATION_STRING_LENGTH_THRESHOLD
  end

  def max_files
    metadata.max_files.presence || '0'
  end

  def conditionals
    Array(metadata['conditionals']).map do |conditional_metadata|
      MetadataPresenter::Conditional.new(conditional_metadata)
    end
  end

  private

  def validation_bundle_key
    @validation_bundle_key ||=
      if type.in?(VALIDATION_BUNDLES.keys)
        definition_bundle = VALIDATION_BUNDLES[type]
        "validations.#{definition_bundle}_bundle"
      end
  end
end

app/models/metadata_presenter/conditional.rb
module MetadataPresenter
  class Conditional < MetadataPresenter::Metadata
    def ==(other)
      metadata.to_h.deep_symbolize_keys == other.metadata.to_h.deep_symbolize_keys
    end

    def expressions
      Array(metadata.expressions).map do |expression|
        MetadataPresenter::Expression.new(expression)
      end
    end
  end
end

app/models/metadata_presenter/coordinates.rb
module MetadataPresenter
  class Coordinates
    include BranchDestinations

    def initialize(service)
      @service = service
      @positions = setup_positions
      @branch_spacers = setup_branch_spacers
    end

    attr_reader :positions, :branch_spacers

    def set_column(uuid, number)
      positions[uuid][:column] = number
    end

    def set_row(uuid, number)
      positions[uuid][:row] = number
    end

    def uuid_column(uuid)
      positions[uuid][:column]
    end

    def uuid_row(uuid)
      positions[uuid][:row]
    end

    def uuid_at_position(column, row)
      positions.find do |uuid, position|
        if position[:column] == column && position[:row] == row
          return uuid
        end
      end
    end

    def positions_in_column(column_number)
      positions.select { |_, position| position[:column] == column_number }
    end

    def set_branch_spacers_column(branch_uuid, column)
      branch_spacers[branch_uuid].each do |position|
        position[:column] = column
      end
    end

    # The first conditional will always attempt to draw an arrow on the same row
    # as the branch object.
    # Each following conditional needs to have a spacers in order for the frontend
    # to draw an arrow therefore we increment the row number from the branches
    # calculated starting row
    def set_branch_spacers_row(branch_uuid, starting_row)
      branch_spacers[branch_uuid].each.with_index(starting_row) do |position, row|
        position[:row] = row
      end
    end

    private

    attr_reader :service
    attr_writer :positions, :branch_spacers

    def setup_positions
      service.flow.keys.index_with do |_uuid|
        { row: nil, column: nil, previous_flow_uuid: nil, conditional_uuid: nil }
      end
    end

    # This also takes into account the 'OR' expressions which
    # need an additional line for an arrow.
    def setup_branch_spacers
      service.branches.each.with_object({}) do |branch, hash|
        hash[branch.uuid] = initial_spacer(branch)
      end
    end

    def initial_spacer(branch)
      destinations = exiting_destinations_from_branch(branch).map do |uuid|
        { uuid:, row: nil, column: nil }
      end
      has_or_conditionals?(branch) ? destinations.uniq : destinations
    end
  end
end

app/models/metadata_presenter/date_field.rb
module MetadataPresenter
  class DateField
    attr_reader :day, :month, :year

    def initialize(day:, month:, year:)
      @day = day
      @month = month
      @year = year
    end

    def present?
      # rubocop:disable Rails/Present
      !blank?
      # rubocop:enable Rails/Present
    end

    def blank?
      @day.blank? || @month.blank? || @year.blank?
    end
  end
end

app/models/metadata_presenter/email_confirmation.rb
module MetadataPresenter
  class EmailConfirmation
    include ActiveModel::Model

    attr_accessor :email_confirmation

    validates_with EmailConfirmationValidator

    def initialize(email)
      self.email_confirmation = email
    end
  end
end

app/models/metadata_presenter/evaluate_branch_conditionals.rb
module MetadataPresenter
  class EvaluateBranchConditionals
    include ActiveModel::Model
    attr_accessor :service, :flow, :user_data

    def page
      evaluated_page_uuid = page_uuid || flow.default_next

      service.find_page_by_uuid(evaluated_page_uuid)
    end

    def page_uuid
      @results ||= conditionals.map do |conditional|
        evaluated_expressions = conditional.expressions.map do |expression|
          expression.service = service

          Operator.new(
            expression.operator
          ).evaluate(
            expression.field_label,
            user_data[expression.expression_component.id]
          )
        end

        if conditional.type == 'or' && evaluated_expressions.any?
          conditional.next
        elsif evaluated_expressions.all?
          conditional.next
        end
      end

      @results.flatten.compact.first
    end

    delegate :conditionals, to: :flow
  end
end

app/models/metadata_presenter/evaluate_conditionals.rb
module MetadataPresenter
  class EvaluateConditionals
    include ActiveModel::Model
    attr_accessor :service, :flow, :user_data

    def page
      evaluated_page_uuid = page_uuid || flow.default_next

      service.find_page_by_uuid(evaluated_page_uuid)
    end

    def page_uuid
      @results ||= conditionals.map do |conditional|
        evaluated_expressions = conditional.expressions.map do |expression|
          expression.service = service

          Operator.new(
            expression.operator
          ).evaluate(
            expression.field_label,
            user_data[expression.expression_component.id]
          )
        end

        if conditional.type == 'or' && evaluated_expressions.any?
          conditional.next
        elsif evaluated_expressions.all?
          conditional.next
        end
      end

      @results.flatten.compact.first
    end

    delegate :conditionals, to: :flow
  end
end

app/models/metadata_presenter/evaluate_content_conditionals.rb
module MetadataPresenter
  class EvaluateContentConditionals
    include ActiveModel::Model
    attr_accessor :service, :user_data

    def evaluate_content_components(page)
      displayed_components = []
      page.content_components.map do |content_component|
        next if page.conditionals_uuids_by_type('never').include?(content_component.uuid)

        if page.conditionals_uuids_by_type('always').include?(content_component.uuid)
          displayed_components << content_component.uuid
        end
        if page.conditionals_uuids_by_type('conditional').include?(content_component.uuid)
          displayed_components << uuid_to_include?(content_component)
        end
      end
      displayed_components.compact
    end

    private

    def uuid_to_include?(candidate_component)
      evaluation_conditions = []

      if candidate_component.conditionals.count > 1
        candidate_component.conditionals.each do |conditional|
          evaluation_conditions << if conditional[:_type] == 'and'
                                     evaluate_condition(conditional).flatten.all?
                                   else
                                     evaluate_condition(conditional)
                                   end
        end

        candidate_component.uuid if evaluation_conditions.flatten.any?
      else
        evaluation_conditions << evaluate_condition(candidate_component.conditionals[0])
        candidate_component.uuid if evaluation_conditions.flatten.all?
      end
    end

    def evaluate_condition(conditional)
      evaluation_expressions = []
      conditional.expressions.map do |expression|
        expression.service = service
        case expression.operator
        when 'is'
          evaluation_expressions << check_answer_equal_expression(expression, user_data)
        when 'is_not'
          evaluation_expressions << !check_answer_equal_expression(expression, user_data)
        when 'is_answered'
          evaluation_expressions << user_data[expression.expression_component.id].present?
        when 'is_not_answered'
          evaluation_expressions << user_data[expression.expression_component.id].blank?
        when 'contains'
          evaluation_expressions << check_answer_include_expression(expression, user_data)
        when 'does_not_contain'
          evaluation_expressions << !check_answer_include_expression(expression, user_data)
        end
      end
      evaluation_expressions
    end

    def check_answer_equal_expression(expression, user_data)
      expression.field_label == user_data[expression.expression_component.id]
    end

    def check_answer_include_expression(expression, user_data)
      answer = user_data[expression.expression_component.id]
      return false if answer.blank?

      answer.include?(expression.field_label)
    end
  end
end

app/models/metadata_presenter/expression.rb
module MetadataPresenter
  class Expression < MetadataPresenter::Metadata
    attr_accessor :service

    def ==(other)
      metadata == other.metadata
    end

    def expression_page
      @expression_page ||= service.find_page_by_uuid(page)
    end

    def expression_component
      @expression_component ||= expression_page.find_component_by_uuid(component)
    end

    def expression_field
      expression_component.find_item_by_uuid(field)
    end

    def field_label
      expression_field['label'] if expression_field
    end
  end
end

app/models/metadata_presenter/item.rb
class MetadataPresenter::Item < MetadataPresenter::Metadata
  def id
    label
  end

  def name
    label
  end

  def description
    hint
  end
end

app/models/metadata_presenter/meta_item.rb
class MetadataPresenter::MetaItem < MetadataPresenter::Metadata
end

app/views/metadata_presenter/component/_autocomplete.html.erb
<%=
  f.govuk_collection_select component.id.to_sym,
  component.items,
  :id,
  :name,
  selected: component.value,
  label: { text: input_title },
  hint:  {
      data: { "fb-default-text" => default_text('hint') },
      text: component.hint
    },
  class: "govuk-!-width-two-thirds fb-autocomplete",
  options: {
    include_blank: true
  }
%>

<% if editable? %>
  <%= render partial: '/partials/editable_autocomplete', locals: { component: component } %>
<% end %>

app/views/metadata_presenter/component/_checkbox.html.erb
<%=
  f.govuk_collection_check_boxes component.id.to_sym,
    component.items,
    :id,
    :name,
    :description,
    legend: { text: input_title },
    hint: { text: component.hint }
%>

app/views/metadata_presenter/component/_checkboxes.html.erb
<%=
  f.govuk_collection_check_boxes component.id.to_sym,
    component.items,
    :id,
    :name,
    :description,
    legend: { text: input_title },
    data: {
      controller: 'default-hint-text',
      'default-hint-text-empty-value': default_text('hint'),
      'default-hint-text-hint-class': 'govuk-hint'
    },
    hint: {
      text: component.hint,
      data: { "fb-default-text" => default_text('hint') },
    },
    include_hidden: false
%>

app/views/metadata_presenter/component/_components.html.erb
<div class="components" data-controller="orderable-items">
  <% components.each_with_index do |component, index| %>
    <% if component.type == 'content' %>
      <% next unless (editable? || @page.show_conditional_component?(component.uuid) || single_page_preview?) %>
          <editable-content id="<%= component.id %>"
                            class="fb-editable govuk-!-margin-top-8"
                            type="<%= component.type %>"
                            default-content="<%= default_text('content') %>"
                            content="<%= component.content %>"
                            data-fb-content-id="<%= "page[#{component.collection}[#{index}]]" %>"
                            data-config="<%= component.to_json %>"
                            data-conditional-api-path="<%= editable? ? URI.decode_www_form_component(api_service_edit_conditional_content_path(service.service_id, component.uuid)) : '' %>"
                            data-controller="orderable-item component"
                            data-orderable-item-order-value="<%= component.order || index %>"
                            data-orderable-items-target="orderableItem"
                            data-action="orderable-item:move->orderable-items#reorder 
                                         orderable-item:move->component#focus
                                         orderable-item:orderUpdated->component#update 
                                         questionRemove->component#destroy" 
                            data-orderable-item-moving-class="moving">
                <div class="html">
                  <%= to_html(component.content) %>
                </div>
          </editable-content>
    <% else %>
      <div class="fb-editable govuk-!-margin-top-8"
           id="<%= component.id %>"
           data-fb-content-type="<%= component.type %>"
           data-fb-content-id="<%= "page[#{component.collection}[#{index}]]" %>"
           data-fb-content-data="<%= component.to_json %>"
           data-fb-default-value="<%= default_title(component.type) %>"
           data-fb-default-item-value="<%= default_item_title(component.type) %>"
           data-controller="orderable-item component"
           data-orderable-item-order-value="<%= component.order || index %>"
           data-orderable-items-target="orderableItem"
           data-action="orderable-item:move->orderable-items#reorder 
                        orderable-item:move->component#focus
                        orderable-item:orderUpdated->component#update 
                        questionRemove->component#destroy" 
           data-orderable-item-moving-class="moving">

           <%= render partial: component, locals: {
             f: f,
             component: component,
             component_id: "page[#{component.collection}[#{index}]]",
             input_title: main_title(
               component: component,
               tag: :h2,
               classes: classes
             )
           }
         %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/metadata_presenter/component/_conditional_component_banner.erb
<% if single_page_preview? && editor_preview? && conditional_components_present? %>
  <%= govuk_notification_banner(title_text: 'Important') do |nb|
    nb.with_heading(text: t('presenter.conditional_content.notification'))
  end %>
<% end%>

app/views/metadata_presenter/component/_conditional_component_banner.html.erb
<% if single_page_preview? && !editable? && @page.conditional_components.any? %>
  <%= govuk_notification_banner(title_text: t('presenter.notification_banners.important')) do |nb|
    nb.with_heading(text: t('presenter.conditional_content.notification'))
  end %>
<% end%>

app/views/metadata_presenter/component/_content.html.erb
<%= to_html(component.content) %>

app/views/metadata_presenter/component/_date.html.erb
<%=
  f.govuk_date_field component.id.to_sym,
    hint: {
      data: { "fb-default-text" => default_text('hint') },
      text: component.hint
    },
    legend: { text: input_title },
    segment_names: {
      day: I18n.t('date.day'),
      month: I18n.t('date.month'),
      year: I18n.t('date.year')
    }
%>

app/views/metadata_presenter/component/_email.html.erb
<%=
  f.govuk_email_field component.id.to_sym,
    label: { text: input_title },
    hint: {
      data: { "fb-default-text" => default_text('hint') },
      text: component.hint
    },
    name: "answers[#{component.name}]",
    spellcheck: "false",
    autocomplete: "email"
%>

<% if is_confirmation_email_question?(component._id) %>
  <div class ="govuk-warning-text">
    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
    <strong class="govuk-warning-text__text">
      <%= I18n.t('presenter.confirmation.email_disclaimer_email_question') %>
    </strong>
  </div>
<%end%>

app/views/metadata_presenter/component/_number.html.erb
<%=
  f.govuk_text_field component.id.to_sym,
    label: { text: input_title },
    hint: {
      data: { "fb-default-text" => default_text('hint') },
      text: component.hint
    },
    name: "answers[#{component.name}]",
    width: component.width_class_input.to_i
%>

app/views/metadata_presenter/component/_radios.html.erb
<%=
  f.govuk_collection_radio_buttons component.id.to_sym,
    component.items,
    :id,
    :name,
    :description,
    legend: { text: input_title },
    data: {
      controller: 'default-hint-text',
      'default-hint-text-empty-value': default_text('hint'),
      'default-hint-text-hint-class': 'govuk-hint'
    },
    hint: {
      text: component.hint,
      data: { "fb-default-text" => default_text('hint') },
    },
    bold_labels: false
%>

app/views/metadata_presenter/component/_text.html.erb
<%=
  f.govuk_text_field component.id.to_sym,
    label: { text: input_title },
    hint: {
      data: { "fb-default-text" => default_text('hint') },
      text: component.hint
    },
    name: "answers[#{component.name}]"
%>

app/views/metadata_presenter/component/_textarea.html.erb
<%=
  f.govuk_text_area component.id.to_sym,
    label: { text: input_title },
    hint: {
      data: { "fb-default-text" => default_text('hint'), "fb-node" => "hint" },
      text: component.hint
    },
    name: "answers[#{component.name}]",
    max_chars: component.validation['max_length'],
    max_words: component.validation['max_word'],
    threshold: component.validation_threshold,
    rows: component.rows
%>

app/views/metadata_presenter/component/_upload.html.erb
<% if answered?(component.id) %>
  <%= input_title %>
  <span class="govuk-hint" id="answers-dog-picture-upload-1-hint" data-fb-default-text="<%= default_text('upload_hint') %>">
    <%= component.hint.present? ? component.hint : default_text('upload_hint') %>
  </span>
  <p><%= @page_answers.send(component.id)['original_filename'] %></p>

  <p>
    <%= link_to t('presenter.questions.upload.remove_file'), remove_file_path(component.id), class: 'govuk-link' %>
  </p>
<% else %>
  <%= f.govuk_file_field component.id.to_sym,
    label: { text: input_title },
    hint: {
        data: { "fb-default-text" => default_text('upload_hint') },
        text: component.hint.present? ? component.hint : default_text('upload_hint')
      },
    accept: component.validation['accept'],
    disabled: editable?
  %>
<% end %>